config/routes.rb
Rails.application.routes.draw do
  root to: "tours#show"

  resources :tours, only: [:show] do
    resources :spots, only: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :country
  has_many :spots
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :cities
end

app/models/spot.rb
class Spot < ApplicationRecord
  belongs_to :city
  has_many :tours, through: :tour_stops
end

app/models/tour.rb
class Tour < ApplicationRecord
  has_many :spots, through: :tour_stops
end

app/models/tour_stop.rb
class TourStop < ApplicationRecord
  belongs_to :tour
  belongs_to :spot

  def self.in_tour(tour)
    where(tour: tour)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  def show
    @tour = Tour.first
    @tour_stops = TourStop.in_tour(@tour)
  end

  private

  def tour_params
    params.require(:tour).permit(:name, :price, :rating, :length, :level, :language, :inclusion, :spot_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TourHero</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag "https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/240/apple/198/world-map_1f5fa.png" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_map.html.erb
<div class="map"></div>

app/views/shared/_slider.html.erb
<ul class="slider">
  <li id="slide-1" class="slider__card" >
    <%= image_tag "singapore.jpg", class: "slider__image" %>
  </li>
  <li id="slide-2" class="slider__card">
    <%= image_tag "singapore.jpg", class: "slider__image" %>
    <%#= video_tag "singapore.jpg", class: "slider__video", poster: "singapore.jpg" %>
    <div class="slider__video-button">
      <%= inline_svg_tag "icons/button_play.svg", class: "button-play" %>
    </div>
  </li>
  <li id="slide-3" class="slider__card">
    <%= image_tag "singapore.jpg", class: "slider__image" %>
  </li>
</ul>

app/views/shared/_slider_nav.html.erb
<div class="slider-nav" data-turbolinks="false">
  <%= link_to "", tour_path(tour, anchor: "slide-1" ), class: "slider-nav__item" %>
  <%= link_to "", tour_path(tour, anchor: "slide-2" ), class: "slider-nav__item" %>
  <%= link_to "", tour_path(tour, anchor: "slide-3" ), class: "slider-nav__item" %>
</div>

app/views/shared/_social_bar.html.erb
<div class="social-bar">
  <span class="social-bar__icon">
    <i class="far fa-share-square"></i>
  </span>
  <span class="social-bar__icon">
    <i class="far fa-heart"></i>
  </span>
</div>

app/views/spots/_spot_card.html.erb
<div class="card">
  <span class="card__tag">Day <%= index + 1 %></span>
  <h3 class="card__title"><%= tour_stop.spot.name %></h3>
  <%= image_tag "singapore.jpg", class: "card__image" %>
  <p class="card__text"><%= tour_stop.spot.description %></p>
  <%= link_to "Show more", "#" %>
</div>

app/views/tours/_tour_details.html.erb
<div class="details-grid">
  <div class="details-grid__item">
    <i class="icon far fa-clock"></i>
    <p class="details-grid__item-name">Duration</p>
    <p class="details-grid__item-text"><%= pluralize @tour.length, "day" %></p>
  </div>
  <div class="details-grid__item">
    <i class="icon fas fa-globe"></i>
    <p class="details-grid__item-name">Countries</p>
    <p class="details-grid__item-text">2</p>
  </div>
  <div class="details-grid__item">
    <i class="icon fas fa-running"></i>
    <p class="details-grid__item-name">Activity Level</p>
    <p class="details-grid__item-text"><%= @tour.level %></p>
  </div>
  <div class="details-grid__item">
    <i class="icon fas fa-language"></i>
    <p class="details-grid__item-name">Guide Language</p>
    <p class="details-grid__item-text"><%= @tour.language %></p>
  </div>
  <div class="details-grid__item">
    <i class="icon fas fa-clipboard-check"></i>
    <p class="details-grid__item-name">Inclusion</p>
    <p class="details-grid__item-text">Food, Hotel, Transport</p>
  </div>
</div>

app/views/tours/_tour_garuantees.html.erb
<ul class="list">
  <li class="list__item">
    <span class="list__icon"><i class="icon fas fa-check-circle"></i></span>
    <p>0% Instalment payment</p>
  </li>
  <li class="list__item">
    <span class="list__icon"><i class="icon fas fa-check-circle"></i></span>
    <p>$200 Deposit</p>
  </li>
  <li class="list__item">
    <span class="list__icon"><i class="icon fas fa-check-circle"></i></span>
    <p>24/7 Support</p>
  </li>
  <li class="list__item">
    <span class="list__icon"><i class="icon fas fa-check-circle"></i></span>
    <p>No booking fee</p>
  </li>
  <li class="list__item">
    <span class="list__icon"><i class="icon fas fa-check-circle"></i></span>
    <p>Free cancellation & changes up to 45 days prior </p>
  </li>
</ul>

app/views/tours/show.html.erb
<div class="tour">
  <%= render "shared/slider" %>
  <%= render partial: "shared/slider_nav", locals: { tour: @tour } %>
  <%= render "shared/social_bar" %>
  <div class="tour__header">
    <header class="header">
      <h1 class="header__title"><%= @tour.name %></h1>
      <p>There’s something for everyone―world-class theme parks, iconic waterfront attractions, the world’s first night safari, hidden gems to explore in charming neighbourhoods, lush greenery.</p>
    </header>
  </div>
  <div class="tour__section">
    <%= render "shared/map" %>
  </div>
  <section class="tour__section">
    <div class="tour__details">
      <%= render "tour_details" %>
    </div>
  </section>
  <section class="tour__section">
    <div class="tour__sub-header">
      <div class="sub-header">
        <span class="sub-header__icon">
          <i class="icon fas fa-clipboard-list"></i>
        </span>
        <h2>Buy With Confidence</h2>
      </div>
    </div>
    <%= render "tour_garuantees" %>
  </section>
  <section class="tour__section">
    <div class="tour__sub-header">
      <div class="sub-header">
        <span class="sub-header__icon">
          <i class="icon fas fa-map-marked-alt"></i>
        </span>
        <h2>Itinerary</h2>
      </div>
    </div>
    <% @tour_stops.each_with_index do |tour_stop, index| %>
      <%= render partial: "spots/spot_card", locals: { tour_stop: tour_stop, index: index } %>
    <% end %>
  </section>
  <div class="button">Show more days</div>
</div>